import { Router } from 'express';
import { addressRouter } from './address.routes.js';
import { authRouter } from './auth.routes.js';
import { cartRouter } from './cart.routes.js';
import { categoryRouter } from './category.routes.js';
import { faqRouter } from './faq.routes.js';
import { favoriteRouter } from './favorite.routes.js';
import { notificationRouter } from './notification.routes.js';
import { orderRouter } from './order.routes.js';
import { paymentRouter } from './payment.routes.js';
import { productRouter } from './product.routes.js';
import { promoRouter } from './promo.routes.js';
import { reviewRouter } from './review.routes.js';
import { rewardRouter } from './reward.routes.js';
import { storeRouter } from './store.routes.js';
import { userRouter } from './user.routes.js';

export const apiRouter = Router();
apiRouter.use('/auth', authRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/addresses', addressRouter);
apiRouter.use('/categories', categoryRouter);
apiRouter.use('/stores', storeRouter);
apiRouter.use('/products', productRouter);
apiRouter.use('/cart', cartRouter);
apiRouter.use('/favorites', favoriteRouter);
apiRouter.use('/orders', orderRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use('/promos', promoRouter);
apiRouter.use('/reviews', reviewRouter);
apiRouter.use('/rewards', rewardRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/faqs', faqRouter);
